-- 구버전 테이블 삭제 및 정리
DROP TABLE IF EXISTS POST;

CREATE TABLE IF NOT EXISTS POSTS (
    no BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    views INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS POST_TAGS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    post_no BIGINT NOT NULL,
    tag_name VARCHAR(50) NOT NULL,
    FOREIGN KEY (post_no) REFERENCES POSTS(no) ON DELETE CASCADE
);
